In [ ]:
x_s = [1,2,3,1,2,2,3,4,1,2,3,4,1,2,4]
# COMPLETAR

In [ ]:
# COMPLETAR

¿Cómo te fue con el Challenge? Si no pudiste resolverlo, no te preocupes. ¡NumPy tiene funciones ya incorporadas que calcula algunos estadísticos sobre un arreglo!

### 1.2 Estadística con NumPy

Veamos cómo se calculan, en NumPy, el promedio, varianza y desviación estándar sobre un arreglo.

# Estadística Descriptiva y Pandas

El objetivo del siguiente notebook es, además de repasar conceptos de estadística, que sigas aprendiendo a operar con Numpy y que, además, incorpores Pandas a tu caja de herramientas.

## 1. Estadística Descriptiva

La Estadística Descriptiva nos sirve para comenzar a analizar y entender un conjunto de datos. En el caso de datos numéricos, lo hace obteniendo *valores estadísticos* que, de alguna forma, reemplazan a nuestros datos. Por ejemplo, es muy difícil leer y *entender* la edad de 1000 personas. Pero con un grupo reducido de valores estadísticos (mínimo, máximo, media y desviación estándar, etc.) podemos aproximarnos a ese conjunto de una manera mucho más comprensible. Veamos dos medidas muy importantes:

**Promedio**

Dados $n$ números $x_1,x_2,...,x_n$, el promedio o media es 

$$\overline{x} = \frac{1}{n}\sum_{i=1}^{n} x_i = \frac{x_1 + x_2 + ... + x_n}{n}$$

**Desviación Estándar**

La varianza y la desviación estándar nos dan una idea de cuán "dispersos" están los valores con respecto a su promedio.

$$ Var = \frac{\sum_{i=1}^{n} (x_i -\overline{x})^2}{n - 1}$$

La desviación estándar es la raiz cuadrada de la varianza. En general se usa la letra griega $\sigma$ para representarla o las siglas $SD$:

$$ SD = \sqrt{\frac{\sum_{i=1}^{n} (x_i -\overline{x})^2}{n - 1}}$$

$$ SD = \sqrt{Var}$$


**Comentarios**:
1. Dado un conjunto de números, el promedio suele ser considerado el número más representativo de ese conjunto. Esto no siempre es así. Pensá o googleá por qué.
2. Al conjunto de números $x_1,...,x_n$ los pueden encontrar por el nombre de *población* o *muestra* (¡Ojo que no estamos diciendo que *población* y *muestra* sean lo mismo!).

### Challenge:

Vamos a utilizar de excusa la estadística descriptiva para hacer un desafío de programación:

Dadas la siguiente lista de números, escribir una rutina que calcule su promedio, su varianza y desviación estándar. **Pistas:**
* Probablemente te sea muy útil usar lo que hiciste para ejercicios anteriores.
* Para calcular la varianza y la desviación estándar, usa el resultado que obtuviste al calcular el promedio.

In [5]:
import numpy as np

x_s = np.array([1,2,3,1,2,2,3,4,1,2,3,4,1,2,4])

# Promedio
print(x_s.mean())

# Varianza
print(x_s.var(ddof = 1))

# Desviación estándar
print(x_s.std(ddof = 1))

2.3333333333333335
1.238095238095238
1.1126972805283735


**Para investigar**: ¿qué es el parámetro `ddof` de esa función?¿Qué pasa si no lo usas? Esta pregunta es **difícil** y requiere cierto conocimiento previo. Pero intenta, de todas formas, averiguarlo.

NumPy también puede calcular percentilos (¡googlear!), cuantilos, mínimos y máximos:

In [6]:
print(np.percentile(x_s,75))
print(np.quantile(x_s,0.5))
print(np.min(x_s))
print(np.max(x_s))

3.0
2.0
1
4


**Para investigar**: ¿Cuál es la diferencia entre `np.percentile()` y `np.quantile()`?¿Cómo obtendrías los cuartiles a partir de ellos?

### 1.3 Generación de muestras al azar

Una cosa sumamente útil que podemos hacer con NumPy es generar muestras al azar. Esto no permite simular situaciones. Por ejemplo, las tiradas de dados que aparecen en el GIF de la bitácora. Estas funciones las encontramos dentro del paquete `random` de NumPy, cuya documentación pueden encontrar [aquí](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html). Veamos cómo lo podemos hacer:

In [58]:
muestras_dado = np.random.randint(1,7, size = 15)
print(muestras_dado)

### También se puede
muestras_dado = np.random.choice([1,2,3,4,5,6], size = 15)
print(muestras_dado)

[2 6 2 4 4 2 1 2 3 4 2 4 3 5 5]
[6 3 3 1 6 2 6 3 1 4 5 6 5 1 3]


### Ejercitación

**Ejercicio 1:** ¿Cuál será el promedio de los valores obtenidos al tirar muchas veces un dado?¿Te animás a averiguar - o calcular - cuánto *debería dar* antes de hacerlo? Vamos a tratar de responder esta pregunta **simulando** un dado. Para ello:
* Obtener muestras al azar de un dado usando lo que vimos anteriormente.
* Calcular su promedio y desviación estándar.

¿A partir de qué cantidad de muestras el promedio se "estabiliza"?

In [57]:

dado= np.random.randint(1,7, size = 100000)
#print(dado)
print(dado.mean())
# Desviación estándar
print(dado.std(ddof = 1))


3.4989
1.7060914094734123


**Ejercicio 2:** Simular un dado cargado para favorecer un valor de su elección. Por ejemplo, el seis. Para ello, consultar la ayuda de la función `np.random.choice`. ¿Cómo se modifica el promedio y la desviación estándar?

In [59]:
# COMPLETAR
muestras_dado = np.random.choice([1,2,3,4,5,6], size = 15, replace=True, p=6)

np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

TypeError: ignored

## 2. Pandas 

Pandas es la librería más conocida de Python para manipular y analizar datos. Está montada sobre NumPy, por lo cual muchas funcionalidades son similares. Utilizaremos Pandas para trabajar con datasets estructurados (y bueno, ¡bastante más!). 

Así como NumPy nos proveé de los *arreglos* y con ellos accedemos a muchas nuevas funcionalidades, Pandas nos provee de los *Data Frames* y las *Series*. Por lejos, el objeto más utilizados es el primero, los Data Frames. 


En esta sección empezaremos a:

1. Familiarizarnos con los Data Frames de Pandas, manipular sus funciones básicas y entender la lógica de las mismas (¡para después googlearlas!).
2. Empezar a trabajar con Datasets.

**¡Manos a la obra!**

### 2.1 Primeros pasos

Importamos la librería.

In [61]:
import pandas as pd

Vamos a crear nuestro propio dataset. Es decir, agarrar a mano los datos poblacionales de http://www.ign.gob.ar/nuestrasactividades/geografia/datosargentina/divisionpolitica y guardarlos en una variable `data_dic`.¿Qué tipo de variable es, desde el punto de vista de la programación?

**Nota**: la población está en número de habitantes y la superficie en km2.

In [148]:
data_dic = {"Jurisdiccion":["CABA","Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Jujuy","Mendoza","Misiones","Río Negro","Santa Cruz",
                           "Santa Fe"],"Poblacion":[2890151,15625084,367828,1055259,509108,3308876,673307,1738929,
                                                   1101593,638645,273964,3194537],"Superficie":
           [200,307521,102606,99633,509108,165321,53219,148827,29801,203013,243943,133007]}



Así como podemos crear arreglos a partir de listas, podemos crear Data Frames a partir de diccionarios.

In [149]:
# Creamos el DataFrame
data_pandas = pd.DataFrame(data_dic)
data_pandas

Jurisdiccion  Poblacion  Superficie
0           CABA    2890151         200
1   Buenos Aires   15625084      307521
2      Catamarca     367828      102606
3          Chaco    1055259       99633
4         Chubut     509108      509108
5        Córdoba    3308876      165321
6          Jujuy     673307       53219
7        Mendoza    1738929      148827
8       Misiones    1101593       29801
9      Río Negro     638645      203013
10    Santa Cruz     273964      243943
11      Santa Fe    3194537      133007

**Ejercicio 1:** investigar las funciones que se implementan en la próxima celda. ¿Qué hacen? ¿Para qué piensan que pueden ser útiles?

In [115]:
 #data_pandas.head(3)#muestra los 3 primeros datos
#data_pandas.tail(3)#muestra los 3 últimoos  datos
#data_pandas.count()#conteo de datos
#data_pandas.shape#conteo de filas y columnas


**Ejercicio 2:** agregar al Dataset la información correspondiente a alguna jurisdicción faltante. Recuerden que, al tratarse de una nueva instancia, corresponde a una fila. Pista: googlear "add row to pandas dataframe" o similar. No hay una única forma de hacerlo.

In [150]:
# COMPLETAR

data_dic2 = {"Jurisdiccion":["Cali"],"Poblacion":[12341],"Superficie":
           [123424]}
data_dic2
data_pandas1 = pd.DataFrame(data_dic2)
data_pandas1
data_pandas.append(data_pandas1, ignore_index=True)

Jurisdiccion  Poblacion  Superficie
0           CABA    2890151         200
1   Buenos Aires   15625084      307521
2      Catamarca     367828      102606
3          Chaco    1055259       99633
4         Chubut     509108      509108
5        Córdoba    3308876      165321
6          Jujuy     673307       53219
7        Mendoza    1738929      148827
8       Misiones    1101593       29801
9      Río Negro     638645      203013
10    Santa Cruz     273964      243943
11      Santa Fe    3194537      133007
12          Cali      12341      123424

**Ejercicio 3:** Investigar las funciones columns e index. ¿Qué hacen? ¿Qué tipo de dato es su salida?¿A qué tipo de dato conocido se parecen?

In [134]:
 #data_pandas.columns#nombre de las columnas
 #data_pandas.index#inicio parada y paso
 #data_pandas['Jurisdiccion']

**Ejercicio 4:** ¿Qué hacen las siguientes operaciones?

In [133]:
 #data_pandas['Jurisdiccion']
#data_pandas[['Jurisdiccion','Poblacion']]#para sacar dos columnas
#data_pandas.Jurisdiccion#es igual a la anterior 
#'Poblacion' in data_pandas #población esta en pandas? 

0             CABA
1     Buenos Aires
2        Catamarca
3            Chaco
4           Chubut
5          Córdoba
6            Jujuy
7          Mendoza
8         Misiones
9        Río Negro
10      Santa Cruz
11        Santa Fe
Name: Jurisdiccion, dtype: object

**Ejercicio 5:** Agregar una columna al dataframe que corresponda a la densidad de cada jurisdicción. Usar la información que **ya está** en el dataset.

In [152]:
# COMPLETAR

data_pandas.insert(4, "rios", [3,4,1,12,3,43,2,3,4,3,5,6], True)
data_pandas

Jurisdiccion  rios  Poblacion  Superficie  rios
0           CABA     3    2890151         200     3
1   Buenos Aires     4   15625084      307521     4
2      Catamarca     1     367828      102606     1
3          Chaco    12    1055259       99633    12
4         Chubut     3     509108      509108     3
5        Córdoba    43    3308876      165321    43
6          Jujuy     2     673307       53219     2
7        Mendoza     3    1738929      148827     3
8       Misiones     4    1101593       29801     4
9      Río Negro     3     638645      203013     3
10    Santa Cruz     5     273964      243943     5
11      Santa Fe     6    3194537      133007     6

### 2.2 Filtrado por máscara.

Lo que veremos a continuación es **muy importante**, ya que es una operación que haremos muchas veces. Su implementación es muy parecida tanto en NumPy como en Pandas, por lo que veremos cómo hacerlo primero en NumPy luego en Pandas.

Supongamos que hacemos 50 tiradas de un dado, como hicimos en la sección anterior, pero queremos seleccionar solamente aquellas tiradas que fueron menores que cuatro. ¿Cómo podemos hacerlo?

In [153]:
muestras_dado = np.random.randint(1,7, size = 50)
print(muestras_dado)

[4 4 3 6 4 4 4 2 1 2 5 1 6 5 6 3 5 4 6 2 4 3 6 4 1 4 4 2 1 2 6 5 4 5 2 5 1
 2 1 6 5 5 4 1 2 1 6 5 2 4]


Lo que podemos hacer es crear una máscara:

In [154]:
mascara = muestras_dado < 4
print(mascara)
print(type(mascara))

[False False  True False False False False  True  True  True False  True
 False False False  True False False False  True False  True False False
  True False False  True  True  True False False False False  True False
  True  True  True False False False False  True  True  True False False
  True False]
<class 'numpy.ndarray'>


Notar que `mascara` es un arreglo de booleanos, con `True` en los valores que cumplen la condición y `False` donde no. Una vez que creamos la máscara, podemos usarla para seleccionar de nuestro arreglo aquellos elementos que queríamos:

In [155]:
print(muestras_dado[mascara])

[3 2 1 2 1 3 2 3 1 2 1 2 2 1 2 1 1 2 1 2]


Notar que con `mascara.sum()` podemos contar cuántas veces se cumple la condición que pedimos.

In [156]:
print(mascara.sum())

20


A veces, podemos hacerlo en una sola línea. Supongamos que queremos aquellas tiradas donde salió seis:

In [157]:
print(muestras_dado[muestras_dado == 6])

[6 6 6 6 6 6 6 6]


**En Pandas**

Supongamos que queremos seleccionar aquellas jurisdicciones cuya población sea mayor a un millón de habitantes. Podemos hacerlo de la siguiente forma:

In [158]:
data_pandas[data_pandas.Poblacion > 1000000]

Jurisdiccion  rios  Poblacion  Superficie  rios
0           CABA     3    2890151         200     3
1   Buenos Aires     4   15625084      307521     4
3          Chaco    12    1055259       99633    12
5        Córdoba    43    3308876      165321    43
7        Mendoza     3    1738929      148827     3
8       Misiones     4    1101593       29801     4
11      Santa Fe     6    3194537      133007     6

¿Y si queremos seleccionar aquellas jurisdicciones cuya población sea mayor a un millón de habitantes **y** su superficie menor a cien mil km2?

In [159]:
mascara = np.logical_and(data_pandas.Poblacion > 1000000, data_pandas.Superficie < 100000)
data_pandas[mascara]

### Es equivalente
# data_pandas[(data_pandas.Poblacion > 1000000) & (data_pandas.Superficie < 100000)]

Jurisdiccion  rios  Poblacion  Superficie  rios
0         CABA     3    2890151         200     3
3        Chaco    12    1055259       99633    12
8     Misiones     4    1101593       29801     4

**Ejercicio:** seleccionar aquellas jurisdicciones cuya población sea menor a 500 mil habitantes **o** su superficie mayor a cien mil km2.

In [160]:
# COMPLETAR
mascara = np.logical_and(data_pandas.Poblacion < 500000, data_pandas.Superficie > 100000)
data_pandas[mascara]

Jurisdiccion  rios  Poblacion  Superficie  rios
2     Catamarca     1     367828      102606     1
10   Santa Cruz     5     273964      243943     5

## 2.3 Iris dataset

¿Pero siempre vamos a tener que crear un diccionario y luego pasarlo a un Data Frame? Evidentemente, esta opción no parece muy cómoda, en particular para conjuntos de datos de gran volumen. Veamos cómo trabajamos con un conjunto de datos preexistente.


**Aviso**: Esta sección es, en realidad, un ejercicio. Para hacerlo, debes ir googleando y consultando la documentación que consideres apropiada. Obviamente, también puedes consultar a tu mentor/a.

Vamos a trabajar con el Iris Dataset, probablemente uno de los conjuntos de datos más famosos, ya que muchos ejemplos se realizan con él. Es un dataset sencillo pero ilustrativo.


1. Abrir con Pandas el archivo 'DS_Bitácora_04_iris.csv' (¿Qué tipo de archivo es?) e imprimir sus primeros cinco elementos. Pista: `pd.read...()`.

In [167]:
# COMPLETAR
mi_primer_data=pd.read_csv("/ds_04_Iris.csv")

2. ¿Cuántas columnas (features) tiene?¿Cuáles son sus nombres?¿Y cuántas filas (instancias)? Pistas: `shape`, `columns`.

In [173]:
# COMPLETAR
print(mi_primer_data.shape)

mi_primer_data.columns

(150, 6)


Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

3. Obtener el valor medio y desviación estándar de cada columna. ¿Hay alguna función de Pandas que nos dé aún más estadísticos? Pistas: `describe`.

In [182]:
# COMPLETAR
mi_primer_data.describe()
mi_primer_data

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

4. ¿Creen que todas las columnas tienen información? *Tirar* la columna que crean que está demás. Dependiendo de la función que uses - hay más de una opción -, tal vez tengas que prestar **mucha** atención al argumento `inplace`. Pista: `drop`, `del`.

In [186]:
# COMPLETAR
mi_primer_data.drop(['Id'],axis=1)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

5. ¿Para qué sirven `loc` e `iloc`? Crea algunos ejemplos.